### ISSUE TITLE
Rocket chat : dynamic conversation not working in chat room 

### ISSUE THREAD

**Issue by broferek** [4thParty/hubot-dynamic-conversation#12]
Hi,

Thanks for this really helpfull module !

I have a problem tough.
When sending direct messages to the bot, everything works fine.

When I chat with the bot inside a room, then I have the following issue 

```
Mar 13 12:43:08 sd-49074 hubot[9917]: [Wed Mar 13 2019 12:43:08 GMT+0100 (CET)] ERROR TypeError: Cannot read property 'length' of undefined
Mar 13 12:43:08 sd-49074 hubot[9917]: at Dialog._stripBotName (/opt/infra_install_alephbot/node_modules/hubot-dynamic-conversation/dialog.js:49:32)
Mar 13 12:43:08 sd-49074 hubot[9917]: at Object.handler (/opt/infra_install_alephbot/node_modules/hubot-dynamic-conversation/dialog.js:123:39)
Mar 13 12:43:08 sd-49074 hubot[9917]: at /opt/infra_install_alephbot/node_modules/hubot-conversation/lib/Dialog.js:78:24
Mar 13 12:43:08 sd-49074 hubot[9917]: at Array.some (<anonymous>:null:null)
Mar 13 12:43:08 sd-49074 hubot[9917]: at Dialog.receive (/opt/infra_install_alephbot/node_modules/hubot-conversation/lib/Dialog.js:67:27)
Mar 13 12:43:08 sd-49074 hubot[9917]: at Listener.spy [as callback] (/opt/infra_install_alephbot/node_modules/hubot-conversation/lib/index.js:28:28)
Mar 13 12:43:08 sd-49074 hubot[9917]: at executeListener (/opt/infra_install_alephbot/node_modules/hubot/src/listener.js:79:16)
Mar 13 12:43:08 sd-49074 hubot[9917]: at allDone (/opt/infra_install_alephbot/node_modules/hubot/src/middleware.js:56:7)
Mar 13 12:43:08 sd-49074 hubot[9917]: at /opt/infra_install_alephbot/node_modules/async/lib/async.js:274:13
Mar 13 12:43:08 sd-49074 hubot[9917]: at Object.async.eachSeries (/opt/infra_install_alephbot/node_modules/async/lib/async.js:142:20)
Mar 13 12:43:08 sd-49074 hubot[9917]: at async.reduce (/opt/infra_install_alephbot/node_modules/async/lib/async.js:268:15)
Mar 13 12:43:08 sd-49074 hubot[9917]: at _combinedTickCallback (internal/process/next_tick.js:131:7)
Mar 13 12:43:08 sd-49074 hubot[9917]: at process._tickCallback (internal/process/next_tick.js:180:9)
```
I removed the call to the _stripBotName function in dialog.js and it solved the issue. 

Any help would be appreciated.

Thanks

**Comment by broferek** [comment]
on line 49, nameStrip can be undefined in the case of dialog in a Rocket Chat room

So, this fix below works in both cases, direct message with the bot and dialog in a room
`if (typeof nameStrip !== 'undefined' && text.length == nameStrip.length)`
